### ISSUE TITLE
Does find_subtitle is also yts endpoint

### ISSUE THREAD

**Issue by qadirsuh** [kartouch/yts#1]
Does find_subtitle is also yts endpoint, I am asking so because this is not in yts api official site page
i.e https://yts.ag/api
I couldn't found this

**Comment by kartouch** [comment]
Hey,

Was not even aware yts was back online..
The find_subtitles is not an yts endpoint. It will search on yifysubtitles.
However, I would have to review and test if this gem still works.

**Comment by qadirsuh** [comment]
Hehehe but unfortunately yifysubtitles api are not working nowadays. its 404
